#Cleaning the data

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
android_df = pd.read_csv('android-games.csv')

In [3]:
# Looking at DataFrame snippet
android_df.head()

rank                                         title  total ratings installs  \
0     1                Garena Free Fire- World Series       86273129  500.0 M   
1     2                        PUBG MOBILE - Traverse       37276732  500.0 M   
2     3                     Mobile Legends: Bang Bang       26663595  100.0 M   
3     4                                   Brawl Stars       17971552  100.0 M   
4     5  Sniper 3D: Fun Free Online FPS Shooting Game       14464235  500.0 M   

   average rating  growth (30 days)  growth (60 days)  price     category  \
0               4               2.1               6.9    0.0  GAME ACTION   
1               4               1.8               3.6    0.0  GAME ACTION   
2               4               1.5               3.2    0.0  GAME ACTION   
3               4               1.4               4.4    0.0  GAME ACTION   
4               4               0.8               1.5    0.0  GAME ACTION   

   5 star ratings  4 star ratings  3 star ratings  2 star ratings  \
0        63546766         4949507         3158756         2122183   
1        28339753         2164478         1253185          809821   
2        18777988         1812094         1050600          713912   
3        13018610         1552950          774012          406184   
4         9827328         2124154         1047741          380670   

   1 star ratings   paid  
0        12495915  False  
1         4709492  False  
2         4308998  False  
3         2219794  False  
4         1084340  False

In [4]:
# Noticed that installs is a string and not a number, so checked all the unique install values
android_df.installs.unique()

array(['500.0 M', '100.0 M', '50.0 M', '10.0 M', '5.0 M', '1.0 M',
       '1000.0 M', '500.0 k', '100.0 k'], dtype=object)

In [5]:
# Replace every installs column value with its appropriate integer value
android_df["installs"] = np.where(android_df["installs"] == '1000.0 M', 1000000000, android_df["installs"])
android_df["installs"] = np.where(android_df["installs"] == '500.0 M', 500000000, android_df["installs"])
android_df["installs"] = np.where(android_df["installs"] == '100.0 M', 100000000, android_df["installs"])
android_df["installs"] = np.where(android_df["installs"] == '50.0 M', 50000000, android_df["installs"])
android_df["installs"] = np.where(android_df["installs"] == '10.0 M', 10000000, android_df["installs"])
android_df["installs"] = np.where(android_df["installs"] == '5.0 M', 5000000, android_df["installs"])
android_df["installs"] = np.where(android_df["installs"] == '1.0 M', 1000000, android_df["installs"])
android_df["installs"] = np.where(android_df["installs"] == '500.0 k', 500000, android_df["installs"])
android_df["installs"] = np.where(android_df["installs"] == '100.0 k', 100000, android_df["installs"])

In [6]:
# Convert installs column value to a numeric type (int64 in this case)
android_df["installs"] = pd.to_numeric(android_df["installs"])

In [7]:
# Ensure that the value and type replacements produced correct results
android_df.installs.unique()

array([ 500000000,  100000000,   50000000,   10000000,    5000000,
          1000000, 1000000000,     500000,     100000])

In [8]:
# Examining the DataFrame again to see if it has correct output thus far
android_df.head()

rank                                         title  total ratings  \
0     1                Garena Free Fire- World Series       86273129   
1     2                        PUBG MOBILE - Traverse       37276732   
2     3                     Mobile Legends: Bang Bang       26663595   
3     4                                   Brawl Stars       17971552   
4     5  Sniper 3D: Fun Free Online FPS Shooting Game       14464235   

    installs  average rating  growth (30 days)  growth (60 days)  price  \
0  500000000               4               2.1               6.9    0.0   
1  500000000               4               1.8               3.6    0.0   
2  100000000               4               1.5               3.2    0.0   
3  100000000               4               1.4               4.4    0.0   
4  500000000               4               0.8               1.5    0.0   

      category  5 star ratings  4 star ratings  3 star ratings  \
0  GAME ACTION        63546766         4949507         3158756   
1  GAME ACTION        28339753         2164478         1253185   
2  GAME ACTION        18777988         1812094         1050600   
3  GAME ACTION        13018610         1552950          774012   
4  GAME ACTION         9827328         2124154         1047741   

   2 star ratings  1 star ratings   paid  
0         2122183        12495915  False  
1          809821         4709492  False  
2          713912         4308998  False  
3          406184         2219794  False  
4          380670         1084340  False

In [9]:
# Dropping the paid column because it is redundant with the 'price' column, with a price of 0.0 equalling paid = False
android_df.drop(columns=['paid'], inplace=True)

In [10]:
# Examining the unique values of the price column
android_df.price.unique()

array([0.  , 7.49, 1.99, 2.99, 1.49, 0.99])

In [11]:
# Finding the count of every column
android_df.count()

rank                1730
title               1730
total ratings       1730
installs            1730
average rating      1730
growth (30 days)    1730
growth (60 days)    1730
price               1730
category            1730
5 star ratings      1730
4 star ratings      1730
3 star ratings      1730
2 star ratings      1730
1 star ratings      1730
dtype: int64

In [12]:
# Replacing the 'GAME ' prefix from the category column's values with an empty string
android_df['category'] = android_df['category'].str.replace('GAME ', '')
android_df

rank                                         title  total ratings  \
0        1                Garena Free Fire- World Series       86273129   
1        2                        PUBG MOBILE - Traverse       37276732   
2        3                     Mobile Legends: Bang Bang       26663595   
3        4                                   Brawl Stars       17971552   
4        5  Sniper 3D: Fun Free Online FPS Shooting Game       14464235   
...    ...                                           ...            ...   
1725    96                 زوايا - لعبة ستحرك زوايا عقلك         112408   
1726    97     Bible Word Puzzle - Free Bible Word Games         111595   
1727    98                  Scrabble® GO - New Word Game         110723   
1728    99      Word Nut: Word Puzzle Games & Crosswords         109530   
1729   100                                  Pinturillo 2         108917   

       installs  average rating  growth (30 days)  growth (60 days)  price  \
0     500000000               4               2.1               6.9    0.0   
1     500000000               4               1.8               3.6    0.0   
2     100000000               4               1.5               3.2    0.0   
3     100000000               4               1.4               4.4    0.0   
4     500000000               4               0.8               1.5    0.0   
...         ...             ...               ...               ...    ...   
1725    1000000               4               0.9               1.8    0.0   
1726    1000000               4               0.9               2.3    0.0   
1727   10000000               4               0.9               1.9    0.0   
1728    5000000               4               1.9               4.1    0.0   
1729   10000000               3               1.1               2.5    0.0   

     category  5 star ratings  4 star ratings  3 star ratings  2 star ratings  \
0      ACTION        63546766         4949507         3158756         2122183   
1      ACTION        28339753         2164478         1253185          809821   
2      ACTION        18777988         1812094         1050600          713912   
3      ACTION        13018610         1552950          774012          406184   
4      ACTION         9827328         2124154         1047741          380670   
...       ...             ...             ...             ...             ...   
1725     WORD          101036            3607            3237            1229   
1726     WORD           88950           14856            4297            1385   
1727     WORD           64184           18332            9385            6688   
1728     WORD           99987            4766            1469             953   
1729     WORD           50813           16480           11825            6166   

      1 star ratings  
0           12495915  
1            4709492  
2            4308998  
3            2219794  
4            1084340  
...              ...  
1725            3297  
1726            2103  
1727           12132  
1728            2353  
1729           23631  

[1730 rows x 14 columns]

In [13]:
# Dropping the rows which have duplicate title, category, and total ratings columns.
android_df_no_dup = android_df.loc[android_df.duplicated(subset=["title", "category", "total ratings"]) == False]

In [14]:
# The length of the original DataFrame and the dropped duplicate DataFrame has a difference of 30 rows.
print(len(android_df) - len(android_df_no_dup))
# There are still 25 titles which are duplicated, but they are in different categories or have a different number of total ratings 
print(len(android_df_no_dup) - len(android_df.title.unique()))

30
25


In [15]:
# All of the unique category values
android_df.category.unique()

array(['ACTION', 'ADVENTURE', 'ARCADE', 'BOARD', 'CARD', 'CASINO',
       'CASUAL', 'EDUCATIONAL', 'MUSIC', 'PUZZLE', 'RACING',
       'ROLE PLAYING', 'SIMULATION', 'SPORTS', 'STRATEGY', 'TRIVIA',
       'WORD'], dtype=object)

In [16]:
# All of the unique rank values
android_df["rank"].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [17]:
# Saving the cleaned DataFrame to a CSV file
android_df_no_dup.to_csv(path_or_buf='android-games-clean.csv')